In [1]:
import requests
import json
import pandas as pd
from bs4 import BeautifulSoup as bs

In [2]:
ranks = []
Marks = []
WINDS = []
Competitors = []
DOBS = []
Nats = []
Poss = []
Venues = []
dates = []
ResultScores = []
urls = []

In [3]:
def extract_data(soup):
    # Extract data using BeautifulSoup
    td_tags = soup.find_all('td', {'data-th': 'Rank'})
    for tag in td_tags:
        ranks.append(tag.text.strip())

    Mark = soup.find_all('td', {'data-th': "Mark"})
    for tag in Mark:
        Marks.append(tag.text.strip())

    WIND = soup.find_all('td', {'data-th': "WIND"})
    for tag in WIND:
        WINDS.append(tag.text.strip())

    Competitor = soup.find_all('td', {'data-th': "Competitor"})
    for tag in Competitor:
        Competitors.append(tag.text.strip())

    DOB = soup.find_all('td', {'data-th': "DOB"})
    for tag in DOB:
        DOBS.append(tag.text.strip())

    Nat = soup.find_all('td', {'data-th': "Nat"})
    for tag in Nat:
        Nats.append(tag.text.strip())

    Pos = soup.find_all('td', {'data-th': "Pos"})
    for tag in Pos:
        Poss.append(tag.text.strip())

    Venue = soup.find_all('td', {'data-th': "Venue"})
    for tag in Venue:
        Venues.append(tag.text.strip())

    date = soup.find_all('td', {'data-th': "Date"})
    for tag in date:
        dates.append(tag.text.strip())

    ResultScore = soup.find_all('td', {'data-th': "ResultScore"})
    for tag in ResultScore:
        ResultScores.append(tag.text.strip())

    # Extract URLs
    tbody = soup.find('tbody')
    tags = tbody.find_all('a')
    base_url = 'https://www.worldathletics.org/'
    for tag in tags:
        urls.append(base_url + tag.attrs.get('href', 'Not found'))

# Loop through pages
for i in range(1, 7):
    response = requests.get(f'https://worldathletics.org/records/toplists/road-running/marathon/all/men/senior/2001?regionType=world&page={i}&bestResultsOnly=false&maxResultsByCountry=all&eventId=10229634&ageCategory=senior')
    soup = bs(response.text, 'lxml')

    # Call the function to extract data
    extract_data(soup)

# Now you have all the data in the lists (names, Marks, WINDS, etc.)
# You can use these lists to create a DataFrame or perform further analysis.

In [4]:
athletics_dict = {
    'Rank': ranks,
    'Mark':Marks,
    'WIND':WINDS,
    'Competitor':Competitors,
    'DOB':DOBS,
    'Nat':Nats,
    'Pos':Poss,
    'Venue':Venues,
    'Date':dates,
    'ResultScore':ResultScores,
    'athletes_url':urls
    }

In [5]:
pd.DataFrame(athletics_dict)

,Rank,Mark,WIND,Competitor,DOB,Nat,Pos,Venue,Date,ResultScore,athletes_url
0,1,2:06:50,,Josphat KIPRONO,12 DEC 1973,KEN,1,Rotterdam (NED),22 APR 2001,1213,https://www.worldathletics.org//athletes/athle...
1,2,2:07:02,,Driss EL HIMER,04 APR 1974,FRA,1,Amsterdam (NED),21 OCT 2001,1210,https://www.worldathletics.org//athletes/athle...
2,3,2:07:06,,Josphat KIPRONO,12 DEC 1973,KEN,2,Amsterdam (NED),21 OCT 2001,1209,https://www.worldathletics.org//athletes/athle...
3,4,2:07:11,,Abdelkader EL MOUAZIZ,1969,MAR,1,London (GBR),22 APR 2001,1207,https://www.worldathletics.org//athletes/athle...
4,5,2:07:18,,Kenneth CHERUIYOT,08 FEB 1974,KEN,2,Rotterdam (NED),22 APR 2001,1205,https://www.worldathletics.org//athletes/athle...
...,...,...,...,...,...,...,...,...,...,...,...
565,566,2:16:59,,Franklin TENORIO,30 JUN 1969,ECU,10,Madrid (ESP),28 OCT 2001,1047,https://www.worldathletics.org//athletes/athle...
566,567,2:17:00,,Fabio RINALDI,15 JUL 1973,ITA,1,Parabita (ITA),18 FEB 2001,1047,https://www.worldathletics.org//athletes/athle...
567,567,2:17:00,,Magnus MICHELSSON,04 SEP 1968,AUS,6,Kunsan (KOR),15 APR 2001,1047,https://www.worldathletics.org//athletes/athle...
568,567,2:17:00,,Piotr POB≈ÅOCKI,24 JUL 1965,POL,2,La Rochelle (FRA),25 NOV 2001,1047,https://www.worldathletics.org//athletes/athle...
569,567,2:17:00,,Vitaliy MELTSAYEV,21 JUN 1970,UKR,3,La Rochelle (FRA),25 NOV 2001,1047,https://www.worldathletics.org//athletes/ukrai...

In [6]:
df = pd.DataFrame(athletics_dict)

In [7]:
df.to_csv('results_men_2001.csv', index=False)

In [8]:
import pandas as pd

# Liste des ann√©es
years = list(range(2001, 2025))

# Initialisez un DataFrame vide
union_df = pd.DataFrame()

# Bouclez √† travers les ann√©es et effectuez une union join
for year in years:
    file_path = f"results_men_{year}.csv"
    
    try:
        # Chargez le fichier CSV correspondant √† l'ann√©e
        df = pd.read_csv(file_path)
        
        # Ajoutez une colonne avec l'ann√©e
        df['Year'] = year
        
        # Effectuez une union join avec le DataFrame principal
        union_df = pd.concat([union_df, df], ignore_index=True)
        
        print(f"File {file_path} successfully loaded and union joined.")
    except FileNotFoundError:
        print(f"File {file_path} not found.")

# Affichez le DataFrame avec l'union join
print(union_df)

# Sauvegardez le DataFrame avec l'union join dans un nouveau fichier CSV
union_df.to_csv('union_joined_results_men.csv', index=False)

File results_men_2001.csv successfully loaded and union joined.
File results_men_2002.csv successfully loaded and union joined.
File results_men_2003.csv successfully loaded and union joined.
File results_men_2004.csv successfully loaded and union joined.
File results_men_2005.csv successfully loaded and union joined.
File results_men_2006.csv successfully loaded and union joined.
File results_men_2007.csv successfully loaded and union joined.
File results_men_2008.csv successfully loaded and union joined.
File results_men_2009.csv successfully loaded and union joined.
File results_men_2010.csv successfully loaded and union joined.
File results_men_2011.csv successfully loaded and union joined.
File results_men_2012.csv successfully loaded and union joined.
File results_men_2013.csv successfully loaded and union joined.
File results_men_2014.csv successfully loaded and union joined.
File results_men_2015.csv successfully loaded and union joined.
File results_men_2016.csv successfully loaded and union joined.
File results_men_2017.csv successfully loaded and union joined.
File results_men_2018.csv successfully loaded and union joined.
File results_men_2019.csv successfully loaded and union joined.
File results_men_2020.csv successfully loaded and union joined.
File results_men_2021.csv successfully loaded and union joined.
File results_men_2022.csv successfully loaded and union joined.
File results_men_2023.csv successfully loaded and union joined.
File results_men_2024.csv successfully loaded and union joined.
       Rank     Mark  WIND             Competitor          DOB  Nat    Pos  \
0         1  2:06:50   NaN        Josphat KIPRONO  12 DEC 1973  KEN    1.0
1         2  2:07:02   NaN         Driss EL HIMER  04 APR 1974  FRA    1.0
2         3  2:07:06   NaN        Josphat KIPRONO  12 DEC 1973  KEN    2.0
3         4  2:07:11   NaN  Abdelkader EL MOUAZIZ         1969  MAR    1.0
4         5  2:07:18   NaN      Kenneth CHERUIYOT  08 FEB 1974  KEN    2.0
...     ...      ...   ...                    ...          ...  ...    ...
70393  1296  2:36:56   NaN      Takeshi SAKAGUCHI  25 NOV 1984  JPN  246.0
70394  1296  2:36:56   NaN            Hiroto SATO  07 OCT 1989  JPN  247.0
70395  1298  2:36:57   NaN           Daniel COLOM          NaN  ESP   18.0
70396  1299  2:36:58   NaN     Natsuki FUJIMAGARI          NaN  JPN  179.0
70397  1300  2:37:00   NaN         Kakuda SATOSHI  21 JUL 1983  JPN  248.0

                 Venue         Date  ResultScore  \
0      Rotterdam (NED)  22 APR 2001         1213
1      Amsterdam (NED)  21 OCT 2001         1210
2      Amsterdam (NED)  21 OCT 2001         1209
3         London (GBR)  22 APR 2001         1207
4      Rotterdam (NED)  22 APR 2001         1205
...                ...          ...          ...
70393      Osaka (JPN)  25 FEB 2024          757
70394      Osaka (JPN)  25 FEB 2024          757
70395  Castell√≥n (ESP)  25 FEB 2024          756
70396       Oita (JPN)  04 FEB 2024          756
70397      Osaka (JPN)  25 FEB 2024          756

                                            athletes_url  Year
0      https://www.worldathletics.org//athletes/athle...  2001
1      https://www.worldathletics.org//athletes/athle...  2001
2      https://www.worldathletics.org//athletes/athle...  2001
3      https://www.worldathletics.org//athletes/athle...  2001
4      https://www.worldathletics.org//athletes/athle...  2001
...                                                  ...   ...
70393  https://www.worldathletics.org//athletes/japan...  2024
70394  https://www.worldathletics.org//athletes/japan...  2024
70395  https://www.worldathletics.org//athletes/spain...  2024
70396  https://www.worldathletics.org//athletes/japan...  2024
70397  https://www.worldathletics.org//athletes/athle...  2024

[70398 rows x 12 columns]